---
# ISIS:
#     nsap: 49.0001.0000.0000.0001.00
#     level: level-1-2
#     interfaces:
#         g0/1:
#             sub_iface: G0/1.10
#             encapsulation: dot1q 10
#         g0/2:
#             sub_iface: G0/2.10
#             encapsulation: dot1q 10
#         g0/3:
#             sub_iface: G0/3.10
#             encapsulation: dot1q 10
#         loo0:
#             ipaddr: 1.1.1.1 255.255.255.255

SWITCHPORT:
    interfaces:
        g0/0:
            switchport: disabled
            ipaddr: 10.1.1.30 255.255.255.252
            description: To C1
        g0/1:
            switchport: disabled
            ipaddr: 10.1.1.38 255.255.255.252
            description: To C2
        g0/2:
            switchport: disabled
            ipaddr: 10.1.2.9 255.255.255.252
            description: TO L1
        g0/3:
            switchport: disabled
            ipaddr: 10.1.2.13 255.255.255.252
            description: To L2